[build]
  command = "npm run build"
  publish = "build/client"
  serverBuildPath = "build/server/index.js"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200